server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
# To implement basic security using spring-boot-starter-security dependency
#  security:
#    user:
#      name: AFFSuper
#      password: AFFSuper123

#Enable Eureka client on this MS so that it can register with Eureka Server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
